#!/bin/sh

# 現在のブランチ名を取得
branch=$(git rev-parse --abbrev-ref HEAD)

# main, master, qaブランチではpushできません。
if [ "$branch" = "main" ] || [ "$branch" = "master" ] || [ "$branch" = "qa" ]; then
  echo "❌ $branch ブランチではpushできません。pull request を作成してください。"
  exit 1
fi

echo "✔ チェック完了"
exit 0
